site_name: pytheus

theme:
  name: material

  features:
    - content.code.copy
    - navigation.sections

  icon:
    repo: fontawesome/brands/github

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

repo_name: Llandy3d/pytheus
repo_url: https://github.com/Llandy3d/pytheus

nav:
  - Introduction: 'index.md'
  - Usage:
    - Quickstart: quickstart.md
    - Labels: labels.md
    - Counter: counter.md
    - Gauge: gauge.md
    - Histogram: histogram.md
    - Custom Collector: custom_collector.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
