name: Test

on:
  push:
    branches:
      - "**"

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
      - run: make setup
      - run: make lint
      - run: make pytest
